### ISSUE TITLE
API USAGE LIMITATION

### ISSUE THREAD

**Issue by sathwik-n** [tknishh/ayurvedic-doctor-bot#1]
CAN YOU JUST LET ME KNOW , AN API TO BE USED INSTEAD OF OPENAI , AS IT IS LIMITING

**Comment by tknishh** [comment]
Hi @sathwik-n I believe it'll be better for you to use any open source LLMs from hugging face or go for TheBlokes GGML model that can help you get similar results instead of openAI API
